"""Протоколы, которые ядро объявляет, а внешние слои реализуют.

Зависимости направлены внутрь: ядро ничего не знает о storage, scheduler и telegram.
"""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from kinday.core.models import (
    Account,
    Event,
    Family,
    Invite,
    Membership,
    Person,
    Relation,
    Reminder,
    ReminderOverride,
)


class RecipientBlocked(Exception):
    """Получатель заблокировал бота (Telegram вернул 403)."""


class TransportError(Exception):
    """Сетевой сбой или таймаут при отправке."""


class Clock(Protocol):
    def now(self) -> datetime:
        """Всегда timezone-aware, в UTC."""
        ...


class Notifier(Protocol):
    async def send(self, chat_id: int, text: str) -> None:
        """Поднимает RecipientBlocked при 403 и TransportError при сетевом сбое."""
        ...


class ReminderRepo(Protocol):
    async def claim_due(self, at: datetime, limit: int) -> list[Reminder]: ...
    async def mark_sent(self, reminder_id: int, at: datetime) -> None: ...
    async def mark_missed(self, reminder_id: int, at: datetime) -> None: ...
    async def mark_failed(self, reminder_id: int, at: datetime) -> None: ...
    async def release(self, reminder_id: int) -> None: ...

    async def add_many(self, reminders: list[Reminder]) -> None:
        """Вставляет пачкой. Дубли по уникальному индексу

        (event_id, person_id, occurrence_date, offset_days) молча игнорируются
        (см. SPEC 5.3) — повторная материализация не создаёт дублей.
        """
        ...

    async def delete_future_pending_for_event(self, event_id: int, after: datetime) -> None:
        """Удаляет будущие pending-строки по событию перед перематериализацией (SPEC 5.6)."""
        ...

    async def delete_future_pending_for_person(self, person_id: int, after: datetime) -> None:
        """Удаляет будущие pending-строки по человеку перед перематериализацией (SPEC 5.6)."""
        ...

    async def delete_future_pending_for_event_and_person(
        self, event_id: int, person_id: int, after: datetime
    ) -> None:
        """Удаляет будущие pending-строки одного человека по одному событию.

        Более узкая версия delete_future_pending_for_event: используется, когда
        меняются настройки только одной пары «аккаунт и событие»
        (переопределение, SPEC 5.6) и остальных получателей события трогать не нужно.
        """
        ...

    async def delete_all_for_event(self, event_id: int) -> None:
        """Удаляет все строки по событию независимо от статуса — событие удалено целиком."""
        ...

    async def delete_all_for_person(self, person_id: int) -> None:
        """Удаляет все строки, где человек — получатель, независимо от статуса.

        Используется при удалении человека (SPEC 4.3): в отличие от
        delete_future_pending_for_person, трогает и прошлые строки, потому что
        сам человек как получатель исчезает.
        """
        ...

    async def fail_all_sending(self) -> None:
        """При старте сервиса переводит все строки sending в failed (SPEC 5.5)."""
        ...


class FamilyRepo(Protocol):
    async def get(self, family_id: int) -> Family: ...
    async def create(self, family: Family) -> Family: ...


class PersonRepo(Protocol):
    async def get(self, person_id: int) -> Person: ...
    async def create(self, person: Person) -> Person: ...
    async def update(self, person: Person) -> Person: ...
    async def delete(self, person_id: int) -> None: ...
    async def list_by_family(self, family_id: int) -> list[Person]: ...


class AccountRepo(Protocol):
    async def get(self, account_id: int) -> Account: ...
    async def get_by_telegram_user_id(self, telegram_user_id: int) -> Account | None: ...
    async def save(self, account: Account) -> Account: ...


class MembershipRepo(Protocol):
    async def get_by_account_and_family(
        self, account_id: int, family_id: int
    ) -> Membership | None: ...
    async def list_by_account(self, account_id: int) -> list[Membership]: ...
    async def list_by_family(self, family_id: int) -> list[Membership]: ...
    async def get_by_person(self, person_id: int) -> Membership | None: ...
    async def create(self, membership: Membership) -> Membership: ...
    async def delete(self, person_id: int) -> None: ...


class EventRepo(Protocol):
    async def get(self, event_id: int) -> Event: ...
    async def create(self, event: Event) -> Event: ...
    async def update(self, event: Event) -> Event: ...
    async def delete(self, event_id: int) -> None: ...
    async def list_by_family(self, family_id: int) -> list[Event]: ...
    async def list_by_person(self, person_id: int) -> list[Event]: ...


class RelationRepo(Protocol):
    async def list_by_family(self, family_id: int) -> list[Relation]: ...
    async def add(self, family_id: int, relation: Relation) -> None: ...
    async def remove(self, family_id: int, relation: Relation) -> None: ...


class ReminderOverrideRepo(Protocol):
    async def get(self, account_id: int, event_id: int) -> ReminderOverride | None: ...
    async def set(self, override: ReminderOverride) -> None: ...
    async def revoke(self, account_id: int, event_id: int) -> None: ...


class InviteRepo(Protocol):
    async def get(self, invite_id: int) -> Invite: ...
    async def get_by_code(self, code: str) -> Invite | None: ...
    async def create(self, invite: Invite) -> Invite: ...
    async def revoke(self, invite_id: int, at: datetime) -> None: ...
    async def mark_used(self, invite_id: int, at: datetime) -> None: ...
